sudo: required
language: generic
services:
 - docker

before_install:
 - docker build -t imper4zz/docker-react -f Dockerfile.dev .

script:
 - docker run -e CI=true imper4zz/docker-react npm run test
